# Site settings
title: Giovanni Mendoza
email: mendozagioo@gmail.com
nick: mendozagioo
name: Giovanni Mendoza
description: > # this means to ignore newlines until "baseurl:"
  Hello, this is Giovanni Mendoza, a front-end developer based in Colima
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
