# Site settings
title: Giovanni Mendoza
email: mendozagioo@gmail.com
nick: mendozagioo
name: Giovanni Mendoza
greeting: Hello, I am
description: >
  I am a front-end developer based in Colima, México, focus on web technologies (Javascript, HTML, CSS), UX/UI enthusiast, and creator of
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mendozagioo.me" # the base hostname & protocol for your site
facebook_link: http://facebook.com/MendozaGioo
twitter_link: http://twitter.com/mendozagioo
github_link: http://github.com/mendozagioo

# Build settings
markdown: kramdown
